### ISSUE TITLE
Uniformare il raggruppamento dei comuni in Friuli Venezia Giulia

### ISSUE THREAD

**Issue by LorenzoStucchi** [GISdevio/estratti_OSM_Italia#4]
A seguito della correzione del bug https://github.com/osmItalia/estratti_OSM_Italia/issues/13 è stato creato un'unica area che comprende tutte le provincie del Friuli.
Tuttavia la stessa regione è divisa in area, non chiamate provincie ma [Enti di decentramento regionale](https://it.wikipedia.org/wiki/Ente_di_decentramento_regionale):

- Gorizia https://www.openstreetmap.org/relation/179294
- Trieste https://www.openstreetmap.org/relation/179292
- Pordenone https://www.openstreetmap.org/relation/179293
- Udine https://www.openstreetmap.org/relation/179295

Per essere coerenti a quanto fatto nelle altre regioni, anche per il Friuli Venezia Giulia i comuni dovrebbero essere raggruppati nelle "provincie"

**Comment by frafra** [comment]
A tal proposito è necessario rigenerare il database. La procedura include vari script e non è immediato capire quale eseguire in questo caso.
Potrebbe essere una buona opportunità per migliorare il file README: https://github.com/GISdevio/estratti_OSM_Italia/blob/main/backend/READ.ME.

**Comment by frafra** [comment]
Risolto col commit 3af98231136e1502723f211c63d8802a2692aee4.
